package io.github.vafeen.daggerforge.processor.processing


internal fun copyright() = """
        /**
         * Auto-generated by Dagger Forge. Do not edit.
         *
         * Apache-2.0 license
         *
         * Contact: [vafeen](https://github.com/vafeen)
         */
        """.trimIndent()